// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqfwpsaobbmccjuyvlpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxZndwc2FvYmJtY2NqdXl2bHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTk1MDUsImV4cCI6MjA2NDY5NTUwNX0.-YqK0DaF296UkF_Y_vbxYtOYB31DeLchJgZHaP8eugQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);